### ISSUE TITLE
Support multiple image ID

### ISSUE THREAD

**Issue by bbq-all-stars** [whywaita/myshoes#136]
This project is great!
Thank you for developing it.

By the way, I would like to be able to change an image ID for each target. 
Are there any plans to support multiple image ID?

**Comment by whywaita** [comment]
Hi @bbq-all-stars :)

There is no plan for your suggestion now.

`image ID` (that maybe identification value for OS image) is a specific value for cloud providers.
But myshoes can use in many environments, it includes environments that do not support `image ID`.

Some providers implemented to manage image id. (e.g. [shoes-lxd](https://github.com/whywaita/shoes-lxd/blob/ba85ee778c1c491f010a399bcca1b7f03761c8f0/README.md?plain=1#L40))
Please open the issue in the provider repository if you want to use implemented provider.

**Comment by bbq-all-stars** [comment]
@whywaita 
Thank you for your response!

I understand that this issue is with the provider.
I'm now planning to develop a new provider.
When I do, I'll refer to the show-lxd architecture.

Thanks.
